docs/UserGuide.md

Update UG for second half of Features & Usage:
- `list c`
- `view c <CANDIDATE INDEX>`

Update UserGuide for second half of Features & Usage

---

docs/UserGuide.md

* added title 'User Guide'
* added introduction paragraph
* added FAQs section

Update UserGuide for intro and FAQ

---

docs/DeveloperGuide.md

Edit MSS to omit UI-specific details as notes recommend. Add extensions to all MSS. Remove sample MSS. Edit MSS such that user requests list of candidates first since we have both list candidates and list interviews as features later on.

Add extensions and edit existing MSS.

---

docs/diagrams/UndoRedoState2.puml
src/main/java/seedu/address/logic/parser/CliSyntax.java
src/main/java/seedu/address/logic/parser/Prefix.java

Change prefix from / to =

---

src/main/java/seedu/address/logic/commands/CommandResult.java
src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
src/test/java/seedu/address/logic/commands/EditCommandTest.java
src/test/java/seedu/address/model/person/PersonTest.java
src/test/java/seedu/address/testutil/TypicalPersons.java

Deleted System.out lines use for debugging

Deleted irrelevant lines

---

docs/DeveloperGuide.md
docs/UserGuide.md
src/main/resources/view/MainWindow.fxml

* changed 'Address App' to 'HR Manager'
* removed 'view' command in UserGuide and Developer Guide
* edited phrasing in UserGuide

Update Title of App

---

src/main/java/seedu/address/logic/commands/AddCommand.java
src/main/java/seedu/address/logic/commands/DeleteCommand.java
src/main/java/seedu/address/logic/commands/EditCommand.java
src/main/java/seedu/address/logic/commands/ListCommand.java
src/test/java/seedu/address/logic/LogicManagerTest.java

Fix #35 
add -> add_c
edit -> edit_c
delete -> delete_c
list -> list_c
Update header comments accordingly.
Update test case accordingly.

Change commands to specify candidate

---

src/main/java/seedu/address/commons/core/Messages.java
src/main/java/seedu/address/logic/parser/DeletePositionCommandParser.java
src/main/java/seedu/address/logic/parser/HrManagerParser.java
src/main/java/seedu/address/logic/parser/ParserUtil.java
src/main/java/seedu/address/logic/position/DeletePositionCommand.java
src/test/java/seedu/address/logic/candidate/CommandTestUtil.java
src/test/java/seedu/address/logic/parser/DeletePositionCommandParserTest.java
src/test/java/seedu/address/logic/parser/HrManagerParserTest.java
src/test/java/seedu/address/logic/parser/ParserUtilTest.java
src/test/java/seedu/address/logic/position/DeletePositionCommandTest.java
src/test/java/seedu/address/testutil/PersonUtil.java
src/test/java/seedu/address/testutil/TypicalIndexes.java

* added DeletePositionCommandParser and DeletePositionCommand classes
* added Tests Classes for DeletePositionCommandParser and DeletePositionCommand
* updated various files to support test cases and DeletePoisitionCommand
* added test cases to existing files

Add DeletePositionCommand

---

src/main/java/seedu/address/logic/CommandResult.java
src/main/java/seedu/address/logic/Logic.java
src/main/java/seedu/address/logic/LogicManager.java
src/main/java/seedu/address/logic/candidate/ListCandidateCommand.java
src/main/java/seedu/address/logic/general/ExitCommand.java
src/main/java/seedu/address/logic/general/HelpCommand.java
src/main/java/seedu/address/logic/parser/HrManagerParser.java
src/main/java/seedu/address/logic/position/ListPositionCommand.java
src/main/java/seedu/address/model/Model.java
src/main/java/seedu/address/model/ModelManager.java
src/main/java/seedu/address/ui/DisplayListPanel.java
src/main/java/seedu/address/ui/MainWindow.java
src/main/java/seedu/address/ui/PersonListPanel.java
src/main/java/seedu/address/ui/PositionCard.java
src/main/java/seedu/address/ui/PositionListPanel.java
src/main/resources/view/MainWindow.fxml
src/main/resources/view/PositionListCard.fxml
src/main/resources/view/PositionListPanel.fxml
src/test/java/seedu/address/logic/LogicManagerTest.java
src/test/java/seedu/address/logic/candidate/AddCandidateCommandTest.java
src/test/java/seedu/address/logic/candidate/CommandResultTest.java
src/test/java/seedu/address/logic/candidate/CommandTestUtil.java
src/test/java/seedu/address/logic/candidate/ExitCommandTest.java
src/test/java/seedu/address/logic/candidate/HelpCommandTest.java
src/test/java/seedu/address/logic/parser/HrManagerParserTest.java
src/test/java/seedu/address/logic/position/AddPositionCommandTest.java
src/test/java/seedu/address/logic/position/ListPositionCommandTest.java
src/test/java/seedu/address/model/ModelManagerTest.java

Fix #54 
- Implement `list_p` command to display the current position list
- Use the sample space for displaying position list i.e. it replaces existing candidate list if the candiate list is displaying, for consistency in UI
- Displays position index with position title
*Each position is planned to display its status as a tag.*

List position command

---

src/main/java/seedu/address/model/interview/Interview.java
src/test/java/seedu/address/logic/interview/CommandTestUtil.java
src/test/java/seedu/address/model/interview/InterviewTest.java
src/test/java/seedu/address/testutil/InterviewBuilder.java
src/test/java/seedu/address/testutil/TypicalInterviews.java

Fix #59 
The `Interview` class has the following fields:
- 1 `Position`
- A set of candidates
- 1 start time
- 1 duration
- 1 interview status
- `PENDING`
- `COMPLETED`

Create Interview Class

---

src/main/java/seedu/address/model/person/Person.java
src/test/data/JsonSerializableHrManagerCandidatesTest/duplicatePersonHrManager.json
src/test/java/seedu/address/model/person/PersonTest.java

- Updated isSamePerson to include phone and email
- Updated relevant test cases

Update isSamePerson to include phone and email

---

src/main/java/seedu/address/commons/core/Messages.java
src/main/java/seedu/address/logic/interview/DeleteInterviewCommand.java
src/main/java/seedu/address/logic/parser/DeleteInterviewCommandParser.java
src/main/java/seedu/address/logic/parser/HrManagerParser.java
src/test/java/seedu/address/logic/interview/CommandTestUtil.java
src/test/java/seedu/address/logic/interview/DeleteInterviewCommandTest.java
src/test/java/seedu/address/testutil/TypicalIndexes.java
src/test/java/seedu/address/testutil/TypicalPersons.java

-Added delete_i command
-Added relevant test cases
**NOTE: Interviews still not implemented into Person yet. Will do so after this is merged.**

Delete interview command

---

src/main/java/seedu/address/commons/core/Messages.java
src/main/java/seedu/address/logic/interview/FindInterviewCommand.java
src/main/java/seedu/address/model/interview/FindInterviewCommandPredicate.java
src/test/java/seedu/address/logic/interview/FindInterviewCommandTest.java
src/test/java/seedu/address/logic/parser/FindInterviewCommandParserTest.java
src/test/java/seedu/address/model/interview/FindInterviewCommandPredicateTest.java
src/test/java/seedu/address/model/interview/TupleTest.java
src/test/java/seedu/address/testutil/TypicalInterviews.java

* Typical Interviews is not the same as interviews in TypicalPerson
* Predicate tested for candidates only currently

Add test for find_i

---

src/main/java/seedu/address/model/interview/Interview.java
src/main/java/seedu/address/ui/InterviewCard.java

e.g. 18 Oct 2021
And standardize all time period display to "hh:mm ~ hh:mm"
e.g. 13:00 ~ 14:30
Fix #237

Change interview date format to dd mmm yyyy

---

src/main/java/seedu/address/logic/candidate/AddCandidateCommand.java
src/main/java/seedu/address/logic/candidate/EditCandidateCommand.java
src/main/java/seedu/address/logic/candidate/FindCandidateCommand.java
src/main/java/seedu/address/logic/interview/AddInterviewCommand.java
src/main/java/seedu/address/logic/interview/EditInterviewCommand.java
src/main/java/seedu/address/logic/interview/FindInterviewCommand.java
src/main/java/seedu/address/logic/position/AddPositionCommand.java
src/main/java/seedu/address/logic/position/FindPositionCommand.java
src/main/java/seedu/address/model/person/Person.java
src/main/java/seedu/address/ui/ResultDisplay.java

Fix #241 Fix #188 
- Remove display of empty remark in Candidate
- Fix a few formatting issues in command result display
- Fix the error that the position field of `add_c` command was wrongly optional

Fix a few command display issues

---

src/main/java/seedu/address/logic/candidate/EditCandidateCommand.java
src/main/java/seedu/address/logic/interview/EditInterviewCommand.java
src/main/java/seedu/address/logic/interview/UnassignInterviewCommand.java
src/main/java/seedu/address/ui/MainWindow.java
src/test/java/seedu/address/logic/interview/CommandTestUtil.java
src/test/java/seedu/address/logic/interview/EditInterviewCommandTest.java

-Fix edit_i
- Updated order of operation : Checking first before execution
-Fix handleP()
- Update handleP() so it updates the interview list as well
-Improve code quality
Fix #263

Fix edit_i and updated handleP()

---

docs/AboutUs.md
docs/team/jeffzincatz.md

- Fix some errors in PPP
- Update some descriptions of tasks in PPP

Fix error and update PPP

---

docs/AboutUs.md
docs/team/wanyu-l.md

* updated roles and responsibilities in AboutUs
* added full list of PRs reviewed and bugs & suggestions in wanyu-l.md
* added points in some sections of wanyu-l.md

Update AboutUs and wanyu-l.md

---

docs/DeveloperGuide.md

- Fix format for UC02
- Remove unused description in use case

Fix format of DG

---

docs/UserGuide.md

Add lines to separate sections
Format header size of each section to maintain consistency

Add lines to separate sections for readability

---

docs/team/seaweediman.md

- Add back enhancements that were removed

Add back enhancements for PPP
